INSERT INTO mytable(Codigo,Descricao) VALUES (1,'Audi');
INSERT INTO mytable(Codigo,Descricao) VALUES (2,'BMW');
INSERT INTO mytable(Codigo,Descricao) VALUES (3,'Chevrolet');
INSERT INTO mytable(Codigo,Descricao) VALUES (4,'Citröen');
INSERT INTO mytable(Codigo,Descricao) VALUES (5,'Fiat');
INSERT INTO mytable(Codigo,Descricao) VALUES (6,'Ford');
INSERT INTO mytable(Codigo,Descricao) VALUES (7,'Honda');
INSERT INTO mytable(Codigo,Descricao) VALUES (8,'Hyundai');
INSERT INTO mytable(Codigo,Descricao) VALUES (9,'Jeep');
INSERT INTO mytable(Codigo,Descricao) VALUES (10,'Kia');
INSERT INTO mytable(Codigo,Descricao) VALUES (11,'Mitsubishi');
INSERT INTO mytable(Codigo,Descricao) VALUES (12,'Nissan');
INSERT INTO mytable(Codigo,Descricao) VALUES (13,'Peugeot');
INSERT INTO mytable(Codigo,Descricao) VALUES (14,'Renault');
INSERT INTO mytable(Codigo,Descricao) VALUES (15,'Toyota');
INSERT INTO mytable(Codigo,Descricao) VALUES (16,'Volkswagen');


INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'100');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'100 Avant');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'80');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'80 Avant');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'80 Cabriolet');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A1');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A3 Cabriolet');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A3 Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A4');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A4 Avant');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A4 Cabriolet');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A5');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A6');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A6 Avant');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A7');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'A8');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'Allroad Avant');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'Q3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'Q5');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'Q7');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'R8');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'RS2 Avant');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'RS3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'RS3 Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'RS4');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'RS4 Avant');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'RS5');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'RS6');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'RS6 Avant');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'RS7');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'RS Q3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'S3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'S3 Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'S4');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'S4 Avant');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'S5');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'S6');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'S6 Avant');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'S7');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'S8');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'SQ5');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'TT');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'TT RS');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (1,'TTS');


INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'1M');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'2800');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'I3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'I8');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'M2');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'M3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'M3 Cabrio');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'M3 Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'M4');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'M5');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'M5 Touring');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'M6');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 1');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 1 Cabrio');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 1 Coupé');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 2');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 3 Cabrio');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 3 Compact');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 3 Coupé');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 3 Touring');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 4');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 5');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 5 Touring');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 6 Cabrio');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 6 Coupé');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 6 Gran Coupé');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 7');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Série 8');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'X1');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'X2');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'X3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'X4');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'X5');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'X6');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Z3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Z4 Coupé');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Z4 Roadster');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (2,'Z8');

INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'A10');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'A20');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Agile');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Astra Hatch');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Astra Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Astra Wagon');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Astrovan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Bel Air');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Blazer');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Bonanza');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Brasil');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Brasinca');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'C10');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'C14');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'C20');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Calibra Coupe');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Camaro');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Caprice Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Caprice Wagon');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Captiva');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Caravan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Cavalier');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Celta');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Chevette Hatch');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Chevette Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Chevy 500');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Cheyenne');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Classic');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Cobalt');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Colorado');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Corsa Hatch');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Corsa Pick-Up');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Corsa Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Corsa Wagon');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Corsica Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Corvette');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Cruze');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Cruze Sport6');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'D10');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'D20');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Equinox');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'HHR');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Impala');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Ipanema');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Kadett');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Kadett Conversivel');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Lumina APV');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Lumina Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Malibu');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Marajo');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Meriva');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Montana');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Montana Combo');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Monza');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Monza Hatch');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Omega');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Onix');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Opala');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Opala Coupe');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Pick Up Chevrolet');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Prisma');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'S10 Cabine Dupla');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'S10 Cabine Simples');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Silverado');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Sonic');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Sonic Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Space Van');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Spin');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'SS10');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'SSR');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Suburban');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Suprema');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Tigra');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Tracker');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Trafic');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'TrailBlazer');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Vectra');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Vectra GT');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Veraneio');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (3,'Zafira');

INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Aircross');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'AX');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Berlingo');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'BX');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C3 Picasso');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C4');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C4 Cactus');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C4 Lounge');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C4 Pallas');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C4 Picasso');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C4 VTR');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C5');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C5 Break');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C5 Tourer');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C6');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'C8');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'DS3');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'DS4');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'DS5');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Evasion');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Grand C4 Picasso');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Jumper');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Jumpy');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Xantia');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Xantia Break');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'XM');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'XM Break');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Xsara');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Xsara Break');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Xsara Coupe');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'Xsara Picasso');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (4,'ZX');


INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'147');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'147 Furgao');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'147 Pick-Up');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'500');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Argo');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Brava');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Bravo');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Cinquecento');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Coupe');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Cronos');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Doblò');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Doblò Cargo');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Ducato');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Duna');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Elba');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Fiorino');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Fiorino Pick-Up');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Freemont');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Grand Siena');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Idea');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Linea');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Marea');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Marea Weekend');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Mobi');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Oggi');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Palio');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Palio Weekend');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Panorama');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Premio');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Punto');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Punto Cabrio');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Siena');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Stilo');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Strada');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Tempra');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Tipo');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Toro');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Uno');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Uno Furgão');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Uno Mille');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Uno Pick-Up');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (5,'Weekend');

INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Aerostar');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Aspire');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Belina');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Bronco');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Club Wagon');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Contour');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Corcel');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Coupe Deluxe');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Courier');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Courier Van');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Crown Victoria');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Del Rey');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Del Rey Belina / Scala');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'EcoSport');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Edge');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Escape');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Escort');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Escort Conversivel');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Escort Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Escort SW');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Excursion');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Expedition');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Explorer');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'F-1');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'F-100');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'F-1000');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'F-150');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'F-250');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'F-350');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'F-4000');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'F75');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Fairlane');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Fiesta Hatch');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Fiesta Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Focus Hatch');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Focus Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Ford 1929');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Furglaine');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Fusion');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Galaxie');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'GT');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Ibiza');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Jeep');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Ka+');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Ka Hatch');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Landau');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Lincoln');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Maverick');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Mondeo');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Mondeo Wagon');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Mustang');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'New Fiesta Hatch');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'New Fiesta Sedan');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Pampa');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Probe');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Ranger (Cabine Dupla)');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Ranger (Cabine Simples-Estendida)');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Rural');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Taurus');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Taurus Wagon');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Thunderbird');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Transit');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Verona');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Versailles');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Versailles Royale');
INSERT INTO mytable(Codigo_Marca,Descrição) VALUES (6,'Windstar');


